Repository Lina0Elman/DineDelight, pull requests merged in 2025-03, with the labels that each got.

#14 Feat add reviews add image blobs
  app/src/main/java/com/example/dineDelight/models/Image.kt
  app/src/main/java/com/example/dineDelight/models/Review.kt
  app/src/main/java/com/example/dineDelight/pages/RestaurantReviewsScreen.kt
  app/src/main/java/com/example/dineDelight/pages/UserReviewsScreen.kt
  app/src/main/java/com/example/dineDelight/repositories/ImageRepository.kt
  app/src/main/java/com/example/dineDelight/repositories/ReviewRepository.kt
  app/src/main/java/com/example/dineDelight/utils/BlobUtils.kt
Labels: documentation, enhancement

#19 Issue 16
  app/src/main/java/com/example/dineDelight/utils/BlobUtils.kt
Labels: bug, enhancement

#26 Add A Loading Spinner To My Reservations Screen When The Data Is Loading
  app/src/main/java/com/example/dineDelight/pages/UserReservationsScreen.kt
Labels: bug, enhancement

#27 Fix Show Message When There Are Unavailable Slots When Updating A Reservation
  app/src/main/java/com/example/dineDelight/pages/UpdateReservationScreen.kt
Labels: bug

#28 Fix Fetch Reservations From Firestore On Initialization Of Repository
  app/src/main/java/com/example/dineDelight/repositories/ReservationRepository.kt
Labels: bug

#29 Fix Email Text Dissapear When Pressing The Logout Button
  app/src/main/java/com/example/dineDelight/pages/ProfileScreen.kt
Labels: bug

#30 fixed showing restaurant name in review
  app/src/main/java/com/example/dineDelight/pages/UpdateReviewScreen.kt
  app/src/main/java/com/example/dineDelight/pages/UserReviewsScreen.kt
Labels: bug

#32 Feat add confirmation on delete
  app/src/main/java/com/example/dineDelight/pages/UserReservationsScreen.kt
  app/src/main/java/com/example/dineDelight/pages/UserReviewsScreen.kt
Labels: enhancement

#31 Remove Image Selected Text Log When Posting A Review
  app/src/main/java/com/example/dineDelight/pages/RestaurantReviewsScreen.kt
Labels: bug

#33 Add Build Artifacts With GitHub Actions CI
  .github/workflows/build-artifacts.yaml
  .github/workflows/publish-build-artifacts.yaml
Labels: documentation, enhancement

#37 Feat shrink image size
  README.md
  app/src/main/java/com/example/dineDelight/pages/ProfileScreen.kt
  app/src/main/java/com/example/dineDelight/pages/RestaurantReviewsScreen.kt
  app/src/main/java/com/example/dineDelight/pages/UpdateReviewScreen.kt
  app/src/main/java/com/example/dineDelight/repositories/ImageRepository.kt
Labels: bug, enhancement

#38 Sort Reviews By Descending Order In My Reviews
  app/src/main/java/com/example/dineDelight/pages/UserReviewsScreen.kt
Labels: enhancement

#39 Trim Email And Username On Submit
  app/src/main/java/com/example/dineDelight/pages/LoginScreen.kt
  app/src/main/java/com/example/dineDelight/pages/ProfileScreen.kt
  app/src/main/java/com/example/dineDelight/pages/RegisterScreen.kt
Labels: enhancement

#40 Feat rename app to dinedelight and add image
  app/src/main/res/ic_launcher-web.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-ldpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/playstore-icon.png
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
