Repository Lina0Elman/DineDelight, pull requests merged in 2025-01, with the labels that each got.

#3 Add Documentation For Setting Up Firebase Connection
  README.md
  docs/SetupFirebaseConnection.md
Labels: documentation

#4 Add login & registration handling using firebase
  app/src/main/java/com/example/dineDelight/MainActivity.kt
  app/src/main/java/com/example/dineDelight/pages/HomeScreen.kt
  app/src/main/java/com/example/dineDelight/pages/LoginScreen.kt
  app/src/main/java/com/example/dineDelight/pages/RegisterScreen.kt
Labels: documentation, enhancement

#6 Feat add initial restaurants in home screen
  app/build.gradle.kts
  app/src/main/java/com/example/dineDelight/MainActivity.kt
  app/src/main/java/com/example/dineDelight/models/Meal.kt
  app/src/main/java/com/example/dineDelight/models/Restaurant.kt
  app/src/main/java/com/example/dineDelight/models/RestaurantMenu.kt
  app/src/main/java/com/example/dineDelight/pages/HomeScreen.kt
  app/src/main/java/com/example/dineDelight/pages/ReservationScreen.kt
  app/src/main/java/com/example/dineDelight/pages/RestaurantDetailsScreen.kt
  app/src/main/java/com/example/dineDelight/repositories/RestaurantRepository.kt
  app/src/main/java/com/example/dineDelight/utils/MealsApi.kt
Labels: enhancement
